name       : vgrep
version    : 0.2.2.0
release    : 2
source     :
    - http://hackage.haskell.org/package/vgrep-0.2.2.0/vgrep-0.2.2.0.tar.gz : 7350df283152a8fc6a9c01fb5c5f7f34625d0649194ace2b9158e5c052716c86
license    : BSD-3-Clause
component  : system.utils
summary    : vgrep is a pager for navigating through grep output.
description: |
    vgrep is a pager for navigating through grep output.
builddeps  :
    - haskell-cabal-file-th
    - haskell-cabal-install
    - haskell-fingertree
    - haskell-generic-deriving
    - haskell-lens
    - haskell-lifted-base
    - haskell-pipes-concurrency
    - haskell-vty
    - haskell-yaml
setup      : |
    sed -i "s|1.3|1.4|g" vgrep.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
